language: node_js
node_js:
- '10'
env:
- NODE_VERSION="10.19.0"
services:
- docker
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - node_modules
jobs:
  include:
  - stage: Prepare
    script:
    - nvm install $NODE_VERSION
  - stage: Build
    script:
    - pwd
    - node -v
    - npm -v
    - npm install
    - npm update
    - npm run-script build --prod
before_install:
- openssl aes-256-cbc -K $encrypted_1432bbc027c3_key -iv $encrypted_1432bbc027c3_iv
  -in auth_config.ts.enc -out auth_config.ts -d
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host 129.194.10.127\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key saberfa0@129.194.10.127 pwd
- nvm install v$NODE_VERSION
